_BASE_: "Base-bagtricks.yml"

DATASETS:
  NAMES: ("MEVID",)
  TESTS: ("MEVID",)

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: "50x"
    PRETRAIN: True
  HEADS:
    EMBEDDING_DIM: 2048

SOLVER:
  MAX_EPOCH: 120
  BASE_LR: 0.008
  OPT: "SGD"
  IMS_PER_BATCH: 128
  CHECKPOINT_PERIOD: 2

TEST:
  EVAL_PERIOD: 2

OUTPUT_DIR: "results/resnet50"
