_BASE_: "Base-bagtricks.yml"

DATASETS:
  NAMES: ("MEVID",)
  TESTS: ("MEVID",)

MODEL:
  BACKBONE:
    NAME: "build_vit_backbone"
    DEPTH: "base"
    FEAT_DIM: 768
    STRIDE_SIZE: [12, 12]
    SIE_COE: 3.0
    DROP_PATH_RATIO: 0.1
    PRETRAIN_PATH: ""
  HEADS:
    EMBEDDING_DIM: 768

SOLVER:
  MAX_EPOCH: 120
  BASE_LR: 0.0001
  OPT: "AdamW"
  MOMENTUM: 0.9
  IMS_PER_BATCH: 128
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 2
  AMP:
    ENABLED: False

TEST:
  EVAL_PERIOD: 2

OUTPUT_DIR: "results/transreid_adamw"
