_BASE_: "Base-bagtricks.yml"

DATASETS:
  NAMES: ("MEVID",)
  TESTS: ("MEVID",)

MODEL:
  BACKBONE:
    NAME: "build_osnet_backbone"
    DEPTH: "x1.0"
    PRETRAIN: True
  HEADS:
    EMBEDDING_DIM: 512

SOLVER:
  MAX_EPOCH: 120
  BASE_LR: 0.003
  OPT: "SGD"
  IMS_PER_BATCH: 128
  CHECKPOINT_PERIOD: 2

TEST:
  EVAL_PERIOD: 2

OUTPUT_DIR: "results/osnet"
