_BASE_: "Base-bagtricks.yml"

DATASETS:
  NAMES: ("MEVID",)
  TESTS: ("MEVID",)

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: "50x"
    WITH_IBN: True
    WITH_NL: True
    PRETRAIN: True

  HEADS:
    POOL_LAYER: "GeneralizedMeanPooling"

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")
    CE:
      EPSILON: 0.1
      SCALE: 1.0
    TRI:
      MARGIN: 0.0
      HARD_MINING: False
      SCALE: 1.0

SOLVER:
  MAX_EPOCH: 120
  BASE_LR: 0.008
  OPT: "SGD"
  IMS_PER_BATCH: 128

OUTPUT_DIR: "/content/drive/MyDrive/MultiCameraTracking/results/agw_r50_ibn_finetuned"
